version: '3'

services:
  facturacionG06:
    build: .
    image: facturacion
    ports:
      - 8080:8081
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tpi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - database

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tpi
    ports:
      - 5432:5432
    networks:
      - database

networks:
  database:
    driver: bridge